<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.26">
  <POU Name="cycle_Bch" Id="{964d7c0c-b99e-4179-8ed6-8486a6ed8032}">
    <Declaration><![CDATA[FUNCTION cycle_Bch : BOOL
VAR_INPUT
	pBch: POINTER TO T_BCH;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[pBch^.ctrl.fbBch.In_bolSensorTrigScan := pBch^.io.In_bolSensorTrigScan;
pBch^.ctrl.fbBch();
pBch^.ctrl.fbBch_Bcc();
pBch^.ctrl.fbBch_Bcc_Bcd();
pBch^.datachn.rSendData.fbFifo();]]></ST>
    </Implementation>
    <ObjectProperties />
  </POU>
</TcPlcObject>