<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.36">
  <POU Name="cycle_Jcl" Id="{6e865e9f-061f-4867-9812-af0b12f64d01}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION cycle_Jcl : BOOL
VAR_INPUT
	pJcl: POINTER TO T_JCL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[pJcl^.ctrl.fbJcl_Tcp();
pJcl^.ctrl.fbJcl();
pJcl^.datachn.rSendData.fbFifo();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>